"""
ceed_operators.py — libCEED matrix-free operators for Dissolve 2.0 PDEs.

GPU operator evaluation without sparse matrix assembly.

Geometry approach
-----------------
libCEED's EVAL_WEIGHT would need physical mesh coordinates wired through a
separate geometry operator.  Instead, we precompute the physical integration
weight (wdetJ = w_q * |det J|) and the geometric diffusion factor
G = J^{-1} J^{-T} using numpy/basix, then pass them as EVAL_NONE coefficient
data.  This bypasses libCEED's geometry system entirely and gives exact results.

For P1 tets the Jacobian is constant per element; wdetJ varies only through
the quadrature weight w_q.  We store 10 values per q-pt:
  [wdetJ, G[0,0], G[0,1], G[0,2], G[1,0], G[1,1], G[1,2], G[2,0], G[2,1], G[2,2]]

QFunction convention (two split output fields)
----------------------------------------------
  out[0] = v  (1 comp, EVAL_INTERP): mass contribution
  out[1] = dv (3 comp, EVAL_GRAD):   diffusion contribution (reference-space flux)
Both use er_u + basis on the output side; libCEED accumulates both into the
same VECTOR_ACTIVE DOF vector via their respective transpose operators.
"""

import os
import ctypes
import numpy as np
from mpi4py import MPI

_DUMMY_QFUNC_PTR = ctypes.CFUNCTYPE(ctypes.c_int)(lambda *args: 0)

try:
    import libceed
    _CEED_AVAILABLE = True
except ImportError:
    _CEED_AVAILABLE = False


def libceed_available():
    return _CEED_AVAILABLE


def make_ceed(use_gpu: bool = True):
    """
    Create a libCEED context.  Tries CUDA backends first when use_gpu=True,
    then falls back to CPU-AVX.  Returns (ceed, backend_name).
    """
    if not _CEED_AVAILABLE:
        raise ImportError(
            "libCEED not found.  Install with:\n"
            "  mamba install libceed -c conda-forge\n"
            "or see https://libceed.org for CUDA build instructions."
        )
    if use_gpu:
        for spec in ("/gpu/cuda/ref", "/gpu/cuda/shared"):
            try:
                return libceed.Ceed(spec), spec.split("/")[-1].upper()
            except Exception:
                pass
    return libceed.Ceed("/cpu/self/avx"), "CPU-AVX"


# ── QFunction source (written to .h file at import time) ──────────────────
# libCEED 0.12+ requires an absolute file path for JIT compilation.

_QFUNC_H_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "dissolve_qfuncs.h")

_QFUNC_SOURCE = r"""
// dissolve_qfuncs.h — libCEED QFunction kernels for Dissolve
// Auto-generated by ceed_operators.py — do not edit.
//
// Geometry convention:
//   in[2] = geom (EVAL_NONE, 10 per q-pt):
//     geom[q*10+0]      = wdetJ = w_q * |det J|
//     geom[q*10+1..9]   = G = J^{-1} J^{-T} flattened row-major (9 components)
//   wdetJ and G are precomputed by ceed_operators.py using numpy/basix so
//   libCEED does not need access to physical mesh coordinates.
//
// Output split:
//   out[0] = v  (INTERP, 1): mass   contribution — B^T will integrate to DOFs
//   out[1] = dv (GRAD,   3): diffusion contribution — (grad B)^T integrates to DOFs
#include <ceed.h>

// ── DiffMassBilinear: a(u,v) = (u/dt,v) + De*(grad_u,grad_v) ──────────
CEED_QFUNCTION(DiffMassBilinear)(void *ctx, const CeedInt Q,
    const CeedScalar *const *in, CeedScalar *const *out) {
  const CeedScalar *u    = in[0];  // values at q-pts          (INTERP, 1)
  const CeedScalar *du   = in[1];  // ref-space grad at q-pts  (GRAD,   3)
  const CeedScalar *geom = in[2];  // [wdetJ, G[0..8]]         (NONE,  10)
  const CeedScalar *c    = in[3];  // [De, inv_dt]              (NONE,   2)
  CeedScalar *v  = out[0];         // mass contribution         (INTERP, 1)
  CeedScalar *dv = out[1];         // diffusion flux            (GRAD,   3)
  for (CeedInt q = 0; q < Q; q++) {
    const CeedScalar wJ  = geom[q*10 + 0];
    const CeedScalar De  = c[q*2 + 0];
    const CeedScalar idt = c[q*2 + 1];
    v[q] = wJ * idt * u[q];
    for (CeedInt i = 0; i < 3; i++) {
      dv[q*3 + i] = 0.0;
      for (CeedInt j = 0; j < 3; j++) {
        dv[q*3 + i] += De * geom[q*10 + 1 + i*3 + j] * du[q*3 + j];
      }
    }
  }
  return 0;
}
"""

try:
    with open(_QFUNC_H_PATH, "w") as _fh:
        _fh.write(_QFUNC_SOURCE)
except Exception:
    pass  # non-writable FS: QFunction build will fail with a clear error


def _qsrc(func_name: str) -> str:
    """Return the absolute path source string for ceed.QFunction()."""
    return f"{_QFUNC_H_PATH}:{func_name}"


# ── Mesh data extraction ───────────────────────────────────────────────────

def extract_ceed_mesh_data(domain, V):
    """
    Extract element connectivity and coordinates from a DOLFINx mesh
    in the format required by libCEED ElemRestriction / Basis objects.

    Returns dict with keys: elem_nodes, coords, num_cells, num_dofs, num_qpts,
                             q_pts, q_wts.
    """
    import basix as _basix

    tdim      = domain.topology.dim
    num_cells = domain.topology.index_map(tdim).size_local
    num_dofs  = V.dofmap.index_map.size_local

    dofmap     = V.dofmap
    elem_nodes = np.array(
        [dofmap.cell_dofs(i) for i in range(num_cells)], dtype=np.int32
    )
    coords = domain.geometry.x[:, :3].copy()

    q_pts, q_wts = _basix.make_quadrature(_basix.CellType.tetrahedron, 2)
    num_qpts     = len(q_wts)

    return {
        "elem_nodes": elem_nodes,
        "coords":     coords,
        "num_cells":  num_cells,
        "num_dofs":   num_dofs,
        "num_qpts":   num_qpts,
        "q_pts":      q_pts,
        "q_wts":      q_wts,
    }


def compute_geometric_factors(coords, elem_nodes, q_wts):
    """
    Vectorised computation of physical-space integration factors for P1 tets.

    For cell i with vertices x0..x3:
      J_i = [x1-x0 | x2-x0 | x3-x0]  (columns are edge vectors, shape 3x3)
      detJ_i = |det(J_i)|
      Jinv_i = J_i^{-1}
      G_i    = Jinv_i @ Jinv_i.T       (symmetric 3x3, used in diffusion)

    Per q-point q in cell i:
      wdetJ_iq = q_wts[q] * detJ_i
      G_iq     = G_i  (constant for P1)

    Returns flat array of shape (num_cells * num_qpts * 10,):
      [wdetJ, G[0,0], G[0,1], G[0,2], G[1,0], ..., G[2,2]]  per q-pt.
    """
    nc    = len(elem_nodes)
    nqpts = len(q_wts)

    # node coordinates: (nc, 4, 3)
    cell_coords = coords[elem_nodes]

    # Jacobian columns are edge vectors from vertex 0: (nc, 3, 3)
    # edges[i, j, :] = x[i, j+1, :] - x[i, 0, :]
    edges = cell_coords[:, 1:, :] - cell_coords[:, 0:1, :]  # (nc, 3, 3)
    # J[i, :, j] = edges[i, j, :] → J = edges.transpose(0, 2, 1)
    J = edges.transpose(0, 2, 1)                              # (nc, 3, 3)

    detJ = np.abs(np.linalg.det(J))                          # (nc,)
    Jinv = np.linalg.inv(J)                                  # (nc, 3, 3)
    G    = Jinv @ Jinv.transpose(0, 2, 1)                    # (nc, 3, 3)
    G_flat = G.reshape(nc, 9)                                 # (nc, 9)

    # Assemble geom: (nc, nqpts, 10)
    geom = np.zeros((nc, nqpts, 10), dtype=np.float64)
    for q in range(nqpts):
        geom[:, q, 0]    = q_wts[q] * detJ   # wdetJ
        geom[:, q, 1:10] = G_flat             # G

    return geom.reshape(-1)


def build_elem_restriction(ceed, elem_nodes, num_dofs, num_comp=1):
    """Build a libCEED ElemRestriction from the element DOF map."""
    num_cells, nodes_per_cell = elem_nodes.shape
    offsets = elem_nodes.flatten().astype(np.int32)
    return ceed.ElemRestriction(
        num_cells, nodes_per_cell, num_comp, 1, num_dofs * num_comp,
        offsets, memtype=libceed.MEM_HOST, cmode=libceed.COPY_VALUES
    )


def build_simplex_basis(ceed, num_comp=1):
    """
    Build a libCEED H1 Basis for P1 tetrahedral elements using basix.
    BasisH1 (not BasisTensorH1Lagrange, which is for hex elements only).
    Returns (basis, num_qpts).
    """
    import basix

    cell      = basix.CellType.tetrahedron
    num_nodes = 4

    q_pts, q_wts = basix.make_quadrature(cell, 2)
    num_qpts     = len(q_wts)

    elem = basix.create_element(basix.ElementFamily.P, cell, 1)
    tab  = elem.tabulate(1, q_pts)   # (1+dim, num_qpts, num_nodes, 1)

    interp = np.ascontiguousarray(tab[0, :, :, 0], dtype=np.float64).flatten()
    grad   = np.ascontiguousarray(tab[1:4, :, :, 0], dtype=np.float64).flatten()

    basis = ceed.BasisH1(
        libceed.TET,
        num_comp,
        num_nodes,
        num_qpts,
        interp,
        grad,
        np.ascontiguousarray(q_pts, dtype=np.float64).flatten(),
        np.ascontiguousarray(q_wts, dtype=np.float64),
    )
    return basis, num_qpts


# ── High-level operator ────────────────────────────────────────────────────

class CeedDiffusionMassOp:
    """
    Matrix-free operator: a(u,v) = (u/dt, v) + De*(grad_u, grad_v).
    Used for Cl, OH, O2, and Zn diffusion terms.

    Physical-space correctness is achieved by precomputing:
      geom[q*10+0]   = wdetJ = w_q * |det J|
      geom[q*10+1:10]= G = J^{-1} J^{-T} (maps reference gradients to physical)
    and passing them as EVAL_NONE coefficients.  No EVAL_WEIGHT is used.

    Output fields share er_u + basis:
      "v"  (EVAL_INTERP) — B^T accumulates mass contribution to DOFs
      "dv" (EVAL_GRAD)   — (grad B)^T accumulates diffusion to DOFs
    """

    def __init__(self, ceed, mesh_data, De_vals, inv_dt, num_comp=1):
        self.ceed      = ceed
        self.mesh_data = mesh_data
        self.De_vals   = De_vals
        self.inv_dt    = inv_dt
        self._build(num_comp)

    def _build(self, num_comp):
        ceed  = self.ceed
        md    = self.mesh_data
        nc    = md["num_cells"]
        ndofs = md["num_dofs"]
        nqpts = md["num_qpts"]
        dim   = 3

        # ── Element restrictions ──────────────────────────────────────────
        # er_u: DOF-space restriction for VECTOR_ACTIVE fields
        self.er_u = build_elem_restriction(ceed, md["elem_nodes"], ndofs, num_comp)

        # er_geom: strided q-pt restriction for precomputed geometry (EVAL_NONE)
        self.er_geom = ceed.StridedElemRestriction(
            nc, nqpts, 10, nc * nqpts * 10,
            np.array([10, 1, nqpts * 10], dtype=np.int32)
        )

        # er_coeff: strided q-pt restriction for [De, inv_dt] (EVAL_NONE)
        self.er_coeff = ceed.StridedElemRestriction(
            nc, nqpts, 2, nc * nqpts * 2,
            np.array([2, 1, nqpts * 2], dtype=np.int32)
        )

        # ── P1 simplex basis (reference-space gradients from basix) ───────
        self.basis, _ = build_simplex_basis(ceed, num_comp=num_comp)

        # ── Geometric factor vector ───────────────────────────────────────
        geom_flat = compute_geometric_factors(
            md["coords"], md["elem_nodes"], md["q_wts"]
        )
        self.geom_vec = ceed.Vector(len(geom_flat))
        self.geom_vec.set_array(geom_flat, memtype=libceed.MEM_HOST,
                                cmode=libceed.COPY_VALUES)

        # ── PDE coefficient vector [De, inv_dt] ──────────────────────────
        coeff_flat = self._make_coeff_array(self.De_vals, self.inv_dt, nc, nqpts, md)
        self.coeff_vec = ceed.Vector(len(coeff_flat))
        self.coeff_vec.set_array(coeff_flat, memtype=libceed.MEM_HOST,
                                 cmode=libceed.COPY_VALUES)

        # ── QFunction ────────────────────────────────────────────────────
        self.qf = ceed.QFunction(1, _DUMMY_QFUNC_PTR, _qsrc("DiffMassBilinear"))
        self.qf.add_input("u",    num_comp, libceed.EVAL_INTERP)
        self.qf.add_input("du",   dim,      libceed.EVAL_GRAD)
        self.qf.add_input("geom", 10,       libceed.EVAL_NONE)
        self.qf.add_input("coeff", 2,       libceed.EVAL_NONE)
        self.qf.add_output("v",  num_comp, libceed.EVAL_INTERP)
        self.qf.add_output("dv", dim,      libceed.EVAL_GRAD)

        # ── Operator ─────────────────────────────────────────────────────
        self.op = ceed.Operator(self.qf)
        self.op.set_field("u",     self.er_u,     self.basis,        libceed.VECTOR_ACTIVE)
        self.op.set_field("du",    self.er_u,     self.basis,        libceed.VECTOR_ACTIVE)
        self.op.set_field("geom",  self.er_geom,  libceed.BASIS_NONE, self.geom_vec)
        self.op.set_field("coeff", self.er_coeff, libceed.BASIS_NONE, self.coeff_vec)
        # Both outputs accumulate into the same VECTOR_ACTIVE DOF vector
        self.op.set_field("v",  self.er_u, self.basis, libceed.VECTOR_ACTIVE)
        self.op.set_field("dv", self.er_u, self.basis, libceed.VECTOR_ACTIVE)

    @staticmethod
    def _make_coeff_array(De_vals, inv_dt, nc, nqpts, md):
        """Pack [De_cell, inv_dt] per q-point into a flat array."""
        coeff = np.zeros(nc * nqpts * 2, dtype=np.float64)
        for i in range(nc):
            De_cell = float(np.mean(De_vals[md["elem_nodes"][i]]))
            base    = i * nqpts * 2
            for q in range(nqpts):
                coeff[base + q * 2 + 0] = De_cell
                coeff[base + q * 2 + 1] = inv_dt
        return coeff

    def apply(self, u_vec, out_vec):
        """Apply the matrix-free operator: out = A * u"""
        self.op.apply(u_vec, out_vec)

    def update_coeffs(self, De_vals, inv_dt):
        """Refresh PDE coefficients each time-step (geometry never changes)."""
        self.De_vals = De_vals
        self.inv_dt  = inv_dt
        md  = self.mesh_data
        arr = self._make_coeff_array(De_vals, inv_dt,
                                     md["num_cells"], md["num_qpts"], md)
        self.coeff_vec.set_array(arr, memtype=libceed.MEM_HOST,
                                 cmode=libceed.COPY_VALUES)
